exclude: migrations/

repos:

- repo: local

  hooks:
    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      args: [--py37-plus]

    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=120, --skip-string-normalization, --target-version=py38]

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

    - id: yesqa
      name: yesqa
      entry: yesqa
      language: system
      types: [python]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]

    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      language: system
      types: [python]
      args: [--py37-plus]


