"""users

Revision ID: 304019cd1e64
Revises: 9c5b0d5c3cf2
Create Date: 2022-05-30 17:19:08.331711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304019cd1e64'
down_revision = '9c5b0d5c3cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=4000), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comment_upvotes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('thread_upvotes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('threads', sa.Column('subreddit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'threads', 'subreddits', ['subreddit_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'subreddit_id')
    op.drop_table('thread_upvotes')
    op.drop_table('comment_upvotes')
    op.drop_table('subreddits')
    # ### end Alembic commands ###
